### ISSUE TITLE
No Endpoints in psx sample project

### ISSUE THREAD

**Issue by thinsoldier** [k42b3/psx#26]
I'm following the instructions here: http://phpsx.org/get-started

I can get the /documentation but the root / and api /population return errors.

```
{
    "success": false,
    "title": "ReflectionException",
    "message": "Class Sample\\Api\\Index does not exist in \/home\/vagrant\/code\/x\/psx\/vendor\/psx\/framework\/src\/Dependency\/ObjectBuilder.php on line 70",
    "trace": "#0 \/home\/vagrant\/code\/x\/psx\/vendor\/psx\/framework\/src\/Dependency\/ObjectBuilder.php(70): ReflectionClass->__construct('Sample\\\\Api\\\\Inde...')\n#1 \/home\/vagrant\/code\/x\/psx\/vendor\/psx\/framework\/src\/Dispatch\/ApplicationStackFactory.php(47): PSX\\Framework\\Dependency\\ObjectBuilder->getObject('Sample\\\\Api\\\\Inde...', Array, 'PSX\\\\Framework\\\\A...')\n#2 \/home\/vagrant\/code\/x\/psx\/vendor\/psx\/framework\/src\/Loader\/CallbackResolver\/DependencyInjector.php(59): PSX\\Framework\\Dispatch\\ApplicationStackFactory->getController('Sample\\\\Api\\\\Inde...', Object(PSX\\Http\\Request), Object(PSX\\Http\\Response), Object(PSX\\Framework\\Loader\\Context))\n#3 \/home\/vagrant\/code\/x\/psx\/vendor\/psx\/framework\/src\/Loader\/Loader.php(115): PSX\\Framework\\Loader\\CallbackResolver\\DependencyInjector->resolve(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response), Object(PSX\\Framework\\Loader\\Context))\n#4 \/home\/vagrant\/code\/x\/psx\/vendor\/psx\/framework\/src\/Dispatch\/Dispatch.php(121): PSX\\Framework\\Loader\\Loader->load(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response), Object(PSX\\Framework\\Loader\\Context))\n#5 \/home\/vagrant\/code\/x\/psx\/vendor\/psx\/framework\/src\/Environment\/WebServer\/Engine.php(47): PSX\\Framework\\Dispatch\\Dispatch->route(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response))\n#6 \/home\/vagrant\/code\/x\/psx\/vendor\/psx\/framework\/src\/Environment\/Environment.php(67): PSX\\Framework\\Environment\\WebServer\\Engine->serve(Object(PSX\\Framework\\Dispatch\\Dispatch), Object(PSX\\Framework\\Config\\Config))\n#7 \/home\/vagrant\/code\/x\/psx\/public\/index.php(28): PSX\\Framework\\Environment\\Environment->serve()\n#8 \/home\/vagrant\/code\/x\/psx\/public\/server.php(35): require_once('\/home\/vagrant\/c...')\n#9 {main}",
    "context": "66      }\n67  \n68      public function getObject($className, array $constructorArguments = array(), $instanceOf = null)\n69      {\n<b>70          $class = new ReflectionClass($className);\n<\/b>71  \n72          if ($class-&gt;getConstructor() === null) {\n73              $object = $class-&gt;newInstanceArgs([]);\n74          } else {\n"
}
```

```
{
    "success": false,
    "title": "ReflectionException",
    "message": "Class Sample\\Api\\Population\\Collection does not exist in \/home\/vagrant\/code\/x\/psx\/vendor\/psx\/framework\/src\/Dependency\/ObjectBuilder.php on line 70",
    "trace": "#0 \/home\/vagrant\/code\/x\/psx\/vendor\/psx\/framework\/src\/Dependency\/ObjectBuilder.php(70): ReflectionClass->__construct('Sample\\\\Api\\\\Popu...')\n#1 \/home\/vagrant\/code\/x\/psx\/vendor\/psx\/framework\/src\/Dispatch\/ApplicationStackFactory.php(47): PSX\\Framework\\Dependency\\ObjectBuilder->getObject('Sample\\\\Api\\\\Popu...', Array, 'PSX\\\\Framework\\\\A...')\n#2 \/home\/vagrant\/code\/x\/psx\/vendor\/psx\/framework\/src\/Loader\/CallbackResolver\/DependencyInjector.php(59): PSX\\Framework\\Dispatch\\ApplicationStackFactory->getController('Sample\\\\Api\\\\Popu...', Object(PSX\\Http\\Request), Object(PSX\\Http\\Response), Object(PSX\\Framework\\Loader\\Context))\n#3 \/home\/vagrant\/code\/x\/psx\/vendor\/psx\/framework\/src\/Loader\/Loader.php(115): PSX\\Framework\\Loader\\CallbackResolver\\DependencyInjector->resolve(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response), Object(PSX\\Framework\\Loader\\Context))\n#4 \/home\/vagrant\/code\/x\/psx\/vendor\/psx\/framework\/src\/Dispatch\/Dispatch.php(121): PSX\\Framework\\Loader\\Loader->load(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response), Object(PSX\\Framework\\Loader\\Context))\n#5 \/home\/vagrant\/code\/x\/psx\/vendor\/psx\/framework\/src\/Environment\/WebServer\/Engine.php(47): PSX\\Framework\\Dispatch\\Dispatch->route(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response))\n#6 \/home\/vagrant\/code\/x\/psx\/vendor\/psx\/framework\/src\/Environment\/Environment.php(67): PSX\\Framework\\Environment\\WebServer\\Engine->serve(Object(PSX\\Framework\\Dispatch\\Dispatch), Object(PSX\\Framework\\Config\\Config))\n#7 \/home\/vagrant\/code\/x\/psx\/public\/index.php(28): PSX\\Framework\\Environment\\Environment->serve()\n#8 \/home\/vagrant\/code\/x\/psx\/public\/server.php(35): require_once('\/home\/vagrant\/c...')\n#9 {main}",
    "context": "66      }\n67  \n68      public function getObject($className, array $constructorArguments = array(), $instanceOf = null)\n69      {\n<b>70          $class = new ReflectionClass($className);\n<\/b>71  \n72          if ($class-&gt;getConstructor() === null) {\n73              $object = $class-&gt;newInstanceArgs([]);\n74          } else {\n"
}
```

**Comment by chriskapp** [comment]
Hi, the problem was that the `routes` file contained the wrong namespace for the controller, it should be `App` instead of `Sample` (this was changed in the last release). I have just commited a fix for this and released a new version: https://github.com/apioo/psx-sample/commit/53d0b09237c79a34a4282ad16f686e7d8cb5e4ec
